import type {Client} from './types';
import {defaultNotificationPrefs} from '@/lib/notification-utils';

export const seedClients: Client[] = [
  {
    id: 'client-yasmin',
    name: 'Yasmin K.',
    email: 'yasmin.k@example.com',
    phone: '+971 50 882 4410',
    onboarded: true,
    otpVerified: true,
    otpVerifiedAt: '2026-08-15T11:20:00.000Z',
    suspended: false,
    createdAt: '2026-08-01T08:00:00.000Z',
    lastActiveAt: '2026-08-18T10:30:00.000Z',
    answers: {
      goal: ['build-muscle', 'get-stronger'],
      trainingType: 'both',
      frequency: '3-4',
      startTraining: 'asap',
      days: ['tue', 'thu', 'sat'],
      times: ['evening'],
      routine: 'couple',
      coachGender: 'any',
      style: 'educational',
      gender: 'female',
      age: '23-29',
      ethnicity: 'middle-eastern',
      gymAccess: 'yes',
      languages: ['en', 'ar'],
      location: 'Dubai Marina',
      email: 'yasmin.k@example.com',
      phone: '+971 50 882 4410',
    },
    consents: {
      terms: true,
      privacy: true,
      independent: true,
      contact: true,
      acceptedAt: '2026-08-01T08:45:00.000Z',
    },
    savedCoachIds: ['omar-r', 'sara-m'],
    note: 'Active app demo user — saved Omar and Sara from matches.',
    notificationPrefs: defaultNotificationPrefs,
  },
  {
    id: 'client-reem',
    name: 'Reem A.',
    email: 'reem.a@example.com',
    phone: '+971 50 123 4567',
    onboarded: true,
    otpVerified: true,
    otpVerifiedAt: '2026-08-10T07:15:00.000Z',
    suspended: false,
    createdAt: '2026-08-10T06:50:00.000Z',
    lastActiveAt: '2026-08-17T18:00:00.000Z',
    answers: {
      goal: ['lose-weight'],
      trainingType: 'in-person',
      frequency: '3-4',
      startTraining: 'next-week',
      days: ['mon', 'wed', 'sat'],
      times: ['early-morning'],
      routine: 'hour',
      coachGender: 'female',
      style: 'supportive',
      gender: 'female',
      age: '30-39',
      ethnicity: 'middle-eastern',
      gymAccess: 'yes',
      languages: ['en', 'ar'],
      location: 'Dubai Marina',
      email: 'reem.a@example.com',
      phone: '+971 50 123 4567',
    },
    consents: {
      terms: true,
      privacy: true,
      independent: true,
      contact: true,
      acceptedAt: '2026-08-10T07:10:00.000Z',
    },
    savedCoachIds: ['amina-h'],
    note: 'Beginner, gym access, prefers a female coach and encouraging style.',
    notificationPrefs: {...defaultNotificationPrefs, sms: true},
  },
  {
    id: 'client-tariq',
    name: 'Tariq M.',
    email: 'tariq.m@example.com',
    phone: '+971 55 998 2210',
    onboarded: true,
    otpVerified: true,
    otpVerifiedAt: '2026-08-12T19:40:00.000Z',
    suspended: false,
    createdAt: '2026-08-12T19:00:00.000Z',
    lastActiveAt: '2026-08-16T21:00:00.000Z',
    answers: {
      goal: ['get-stronger', 'build-muscle'],
      trainingType: 'in-person',
      frequency: '3-4',
      startTraining: 'asap',
      days: ['tue', 'thu'],
      times: ['evening'],
      routine: 'couple',
      coachGender: 'male',
      style: 'educational',
      gender: 'male',
      age: '30-39',
      ethnicity: 'middle-eastern',
      gymAccess: 'yes',
      languages: ['en'],
      location: 'Business Bay',
      email: 'tariq.m@example.com',
      phone: '+971 55 998 2210',
    },
    consents: {
      terms: true,
      privacy: true,
      independent: true,
      contact: true,
      acceptedAt: '2026-08-12T19:35:00.000Z',
    },
    savedCoachIds: ['omar-r'],
    note: 'Trains twice a week already, wants structured programming.',
    notificationPrefs: defaultNotificationPrefs,
  },
  {
    id: 'client-dana',
    name: 'Dana S.',
    email: 'dana.s@example.com',
    phone: '+971 52 447 1180',
    onboarded: true,
    otpVerified: true,
    otpVerifiedAt: '2026-08-08T09:00:00.000Z',
    suspended: false,
    createdAt: '2026-08-08T08:30:00.000Z',
    lastActiveAt: '2026-08-14T12:00:00.000Z',
    answers: {
      goal: ['rehab'],
      trainingType: 'in-person',
      frequency: '1-2',
      startTraining: 'two-weeks',
      days: ['any'],
      times: ['morning'],
      routine: 'hour',
      coachGender: 'any',
      style: 'supportive',
      gender: 'female',
      age: '40-49',
      ethnicity: 'prefer-not',
      gymAccess: 'no',
      languages: ['en'],
      location: 'Jumeirah',
      email: 'dana.s@example.com',
      phone: '+971 52 447 1180',
    },
    consents: {
      terms: true,
      privacy: true,
      independent: true,
      contact: true,
      acceptedAt: '2026-08-08T08:55:00.000Z',
    },
    savedCoachIds: [],
    note: 'Lower back discomfort, cleared by physiotherapist.',
    notificationPrefs: {...defaultNotificationPrefs, marketing: true},
  },
  {
    id: 'client-family',
    name: 'Hala T. (parent)',
    email: 'parent@example.com',
    phone: '+971 56 300 7742',
    onboarded: true,
    otpVerified: true,
    otpVerifiedAt: '2026-08-05T14:20:00.000Z',
    suspended: false,
    createdAt: '2026-08-05T13:50:00.000Z',
    lastActiveAt: '2026-08-11T16:30:00.000Z',
    answers: {
      goal: ['sport-beginner'],
      trainingType: 'in-person',
      frequency: '1-2',
      startTraining: 'month',
      days: ['sat', 'sun'],
      times: ['late-afternoon'],
      routine: 'none',
      coachGender: 'any',
      style: 'supportive',
      gender: 'female',
      age: '30-39',
      ethnicity: 'middle-eastern',
      gymAccess: 'no',
      languages: ['en', 'ar'],
      location: 'Al Barsha',
      email: 'parent@example.com',
      phone: '+971 56 300 7742',
    },
    consents: {
      terms: true,
      privacy: true,
      independent: true,
      contact: true,
      acceptedAt: '2026-08-05T14:15:00.000Z',
    },
    savedCoachIds: ['khalid-b'],
    note: 'Two children, ages 7 and 9. Parent will attend sessions.',
    notificationPrefs: defaultNotificationPrefs,
  },
  {
    id: 'client-noor',
    name: 'Noor H.',
    email: 'noor.h@example.com',
    phone: '+971 54 221 9903',
    onboarded: false,
    otpVerified: false,
    otpVerifiedAt: null,
    suspended: false,
    createdAt: '2026-08-17T20:00:00.000Z',
    lastActiveAt: '2026-08-17T20:25:00.000Z',
    answers: {
      goal: ['improve-health'],
      trainingType: 'online',
      frequency: '3-4',
      startTraining: 'asap',
      days: ['any'],
      times: ['any'],
      routine: 'couple',
      coachGender: 'female',
      style: 'supportive',
      gender: 'female',
      age: '23-29',
      ethnicity: 'south-asian',
      gymAccess: 'no',
      languages: ['en'],
      location: 'Online',
      email: 'noor.h@example.com',
      phone: '+971 54 221 9903',
    },
    consents: {
      terms: false,
      privacy: false,
      independent: false,
      contact: false,
      acceptedAt: null,
    },
    savedCoachIds: [],
    note: 'Stopped before OTP/consent — wants calm, low-impact sessions after work.',
    notificationPrefs: {...defaultNotificationPrefs, push: false, email: false},
  },
];
