import type {MarketplaceLead} from './types';

export const seedLeads: MarketplaceLead[] = [
  {
    id: 'l-1024',
    clientId: 'client-reem',
    goal: 'Weight loss',
    serviceId: 8,
    location: 'Dubai Marina',
    frequency: '3x/week',
    format: 'In-person',
    days: 'Mon, Wed, Sat',
    time: 'Early morning (before 9am)',
    matchScore: 92,
    creditCost: 3,
    status: 'open',
    postedAt: '2026-08-18T12:48:00.000Z',
    closedAt: null,
    clientNote: 'Beginner, gym access, prefers a female coach and encouraging style.',
    unlocks: [
      {
        id: 'u-l1024-amina',
        professionalId: 'amina-h',
        credits: 3,
        unlockedAt: '2026-08-18T13:05:00.000Z',
      },
    ],
  },
  {
    id: 'l-1023',
    clientId: 'client-tariq',
    goal: 'Get stronger',
    serviceId: 8,
    location: 'Business Bay',
    frequency: '3–4 times/week',
    format: 'In-person',
    days: 'Tue, Thu',
    time: 'Evening (after 6pm)',
    matchScore: 87,
    creditCost: 3,
    status: 'open',
    postedAt: '2026-08-18T11:30:00.000Z',
    closedAt: null,
    clientNote: 'Trains twice a week already, wants structured programming.',
    unlocks: [
      {
        id: 'u-l1023-omar',
        professionalId: 'omar-r',
        credits: 3,
        unlockedAt: '2026-08-18T12:00:00.000Z',
      },
      {
        id: 'u-l1023-sara',
        professionalId: 'sara-m',
        credits: 3,
        unlockedAt: '2026-08-18T12:15:00.000Z',
      },
    ],
  },
  {
    id: 'l-1022',
    clientId: 'client-dana',
    goal: 'Rehab / injury',
    serviceId: 8,
    location: 'Jumeirah',
    frequency: '1–2 times/week',
    format: 'Client location',
    days: 'Any day',
    time: 'Morning (9am–noon)',
    matchScore: 81,
    creditCost: 4,
    status: 'open',
    postedAt: '2026-08-18T09:00:00.000Z',
    closedAt: null,
    clientNote: 'Lower back discomfort, cleared by physiotherapist.',
    unlocks: [],
  },
  {
    id: 'l-1021',
    clientId: 'client-family',
    goal: 'Learn a sport (beginner)',
    serviceId: 12,
    location: 'Al Barsha',
    frequency: '1–2 times/week',
    format: 'In-person',
    days: 'Sat, Sun',
    time: 'Late afternoon (3–6pm)',
    matchScore: 76,
    creditCost: 2,
    status: 'open',
    postedAt: '2026-08-17T14:00:00.000Z',
    closedAt: null,
    clientNote: 'Two children, ages 7 and 9. Parent will attend sessions.',
    unlocks: [
      {
        id: 'u-l1021-khalid',
        professionalId: 'khalid-b',
        credits: 2,
        unlockedAt: '2026-08-17T16:20:00.000Z',
      },
    ],
  },
  {
    id: 'l-1020',
    clientId: 'client-noor',
    goal: 'Improve health',
    serviceId: 16,
    location: 'Online',
    frequency: '3–4 times/week',
    format: 'Online',
    days: 'Any day',
    time: 'Any time',
    matchScore: 71,
    creditCost: 2,
    status: 'closed',
    postedAt: '2026-08-17T10:00:00.000Z',
    closedAt: '2026-08-17T18:00:00.000Z',
    clientNote: 'Wants calm, low-impact sessions after work.',
    unlocks: [],
  },
];
