import type {Professional} from './types';
import {defaultNotificationPrefs} from '@/lib/notification-utils';

export const seedProfessionals: Professional[] = [
  {
    id: 'amina-h',
    name: 'Amina Haddad',
    email: 'amina.h@halacoach.local',
    phone: '+971 50 111 2233',
    suspended: false,
    createdAt: '2026-01-12T09:00:00.000Z',
    serviceSlugs: ['weight-loss', 'personal-training', 'pre-postnatal'],
    locations: ['mine', 'client', 'online'],
    radiusKm: 8,
    certificationFiles: ['reps-uae-level3.pdf', 'prenatal-cert.pdf'],
    insuranceFiles: ['professional-liability.pdf'],
    verification: 'verified',
    verificationSubmittedAt: null,
    verificationRejectedReason: null,
    activated: true,
    credits: 24,
    txns: [
      {id: 't-amina-1', type: 'purchase', credits: 30, label: 'Growth pack', at: '2026-07-01T10:00:00.000Z'},
      {id: 't-amina-2', type: 'spend', credits: 3, label: 'Lead unlocked', at: '2026-07-14T14:22:00.000Z'},
      {id: 't-amina-3', type: 'spend', credits: 3, label: 'Lead unlocked', at: '2026-08-02T09:15:00.000Z'},
    ],
    specialty: "Weight Loss · Women's Health",
    location: 'Dubai Marina',
    formats: ['In-person', 'Online'],
    languages: ['English', 'Arabic'],
    about:
      'I help women build sustainable habits with calm, progressive training. Sessions are adapted to your energy, schedule and confidence level — progress over perfection.',
    profileCertifications: ['REPs UAE Level 3', 'Pre/Postnatal Specialist', 'CPR & First Aid'],
    years: 8,
    style: 'Supportive / encouraging',
    availability: 'Mon, Wed, Sat · Mornings',
    priceFrom: 'Quote on request',
    gender: 'female',
    rating: 4.9,
    reviews: 128,
    notificationPrefs: defaultNotificationPrefs,
  },
  {
    id: 'omar-r',
    name: 'Omar Rahmani',
    email: 'omar.r@halacoach.local',
    phone: '+971 55 222 3344',
    suspended: false,
    createdAt: '2025-11-03T11:30:00.000Z',
    serviceSlugs: ['personal-training', 'corrective-exercise'],
    locations: ['mine', 'client'],
    radiusKm: 12,
    certificationFiles: ['nasm-cpt.pdf', 'corrective-exercise.pdf'],
    insuranceFiles: ['insurance-2026.pdf'],
    verification: 'verified',
    verificationSubmittedAt: null,
    verificationRejectedReason: null,
    activated: true,
    credits: 18,
    txns: [
      {id: 't-omar-1', type: 'purchase', credits: 30, label: 'Growth pack', at: '2026-06-10T08:00:00.000Z'},
      {id: 't-omar-2', type: 'spend', credits: 4, label: 'Lead unlocked', at: '2026-06-28T16:40:00.000Z'},
      {id: 't-omar-3', type: 'spend', credits: 3, label: 'Lead unlocked', at: '2026-07-19T11:05:00.000Z'},
      {id: 't-omar-4', type: 'spend', credits: 3, label: 'Lead unlocked', at: '2026-08-05T18:20:00.000Z'},
      {id: 't-omar-5', type: 'adjustment', credits: 2, label: 'Support credit', at: '2026-08-10T09:00:00.000Z'},
    ],
    specialty: 'Strength & Conditioning',
    location: 'Business Bay',
    formats: ['In-person', 'Client location'],
    languages: ['English', 'Arabic', 'French'],
    about:
      'Strength coaching for everyday people. Clear programming, honest feedback, and technique first — no ego, no shouting.',
    profileCertifications: ['NASM CPT', 'Corrective Exercise Specialist', 'CPR & First Aid'],
    years: 11,
    style: 'Educational / explanatory',
    availability: 'Tue, Thu, Sun · Evenings',
    priceFrom: 'Quote on request',
    gender: 'male',
    rating: 4.8,
    reviews: 94,
    notificationPrefs: {...defaultNotificationPrefs, marketing: true},
  },
  {
    id: 'sara-m',
    name: 'Sara Mansour',
    email: 'sara.m@halacoach.local',
    phone: '+971 52 333 4455',
    suspended: false,
    createdAt: '2026-02-20T14:00:00.000Z',
    serviceSlugs: ['pilates', 'mobility', 'yoga'],
    locations: ['mine', 'online'],
    radiusKm: 5,
    certificationFiles: ['basi-pilates.pdf'],
    insuranceFiles: ['insurance.pdf'],
    verification: 'verified',
    verificationSubmittedAt: null,
    verificationRejectedReason: null,
    activated: true,
    credits: 7,
    txns: [
      {id: 't-sara-1', type: 'purchase', credits: 10, label: 'Starter pack', at: '2026-05-01T12:00:00.000Z'},
      {id: 't-sara-2', type: 'spend', credits: 3, label: 'Lead unlocked', at: '2026-05-22T10:30:00.000Z'},
    ],
    specialty: 'Pilates · Mobility',
    location: 'Jumeirah',
    formats: ['In-person', 'Online'],
    languages: ['English', 'Arabic'],
    about:
      'Reformer and mat Pilates focused on mobility, posture and calm strength. Great for beginners returning to movement.',
    profileCertifications: ['Comprehensive Pilates (BASI)', 'Mobility Specialist'],
    years: 6,
    style: 'Supportive / encouraging',
    availability: 'Mon–Fri · Mornings',
    priceFrom: 'Quote on request',
    gender: 'female',
    rating: 5,
    reviews: 61,
    notificationPrefs: defaultNotificationPrefs,
  },
  {
    id: 'khalid-b',
    name: 'Khalid Bassam',
    email: 'khalid.b@halacoach.local',
    phone: '+971 56 444 5566',
    suspended: false,
    createdAt: '2025-09-08T08:45:00.000Z',
    serviceSlugs: ['football', 'kids-coach'],
    locations: ['mine', 'client'],
    radiusKm: 15,
    certificationFiles: ['uefa-c.pdf', 'safeguarding.pdf', 'cpr.pdf'],
    insuranceFiles: [],
    verification: 'verified',
    verificationSubmittedAt: null,
    verificationRejectedReason: null,
    activated: true,
    credits: 42,
    txns: [
      {id: 't-khalid-1', type: 'purchase', credits: 75, label: 'Scale pack', at: '2026-04-15T09:00:00.000Z'},
      {id: 't-khalid-2', type: 'spend', credits: 2, label: 'Lead unlocked', at: '2026-05-05T15:00:00.000Z'},
      {id: 't-khalid-3', type: 'spend', credits: 3, label: 'Lead unlocked', at: '2026-06-01T13:20:00.000Z'},
    ],
    specialty: 'Kids Football · Athletic Development',
    location: 'Al Barsha',
    formats: ['In-person', 'Outdoor'],
    languages: ['English', 'Arabic'],
    about:
      'Youth coaching built on confidence and fun. Parents are welcome to watch every session — safety and safeguarding first.',
    profileCertifications: ['UEFA C Licence', 'Safeguarding Children', 'CPR & First Aid'],
    years: 9,
    style: 'Strict / disciplined',
    availability: 'Sat, Sun · Afternoons',
    priceFrom: 'Quote on request',
    gender: 'male',
    rating: 4.7,
    reviews: 143,
    notificationPrefs: defaultNotificationPrefs,
  },
  {
    id: 'leila-k',
    name: 'Leila Karam',
    email: 'leila.k@halacoach.local',
    phone: '+971 54 555 6677',
    suspended: false,
    createdAt: '2026-08-10T16:20:00.000Z',
    serviceSlugs: ['life-coaching', 'stress-burnout', 'mindfulness'],
    locations: ['online'],
    radiusKm: 10,
    certificationFiles: ['icf-acc.pdf'],
    insuranceFiles: [],
    verification: 'pending',
    verificationSubmittedAt: '2026-08-17T09:30:00.000Z',
    verificationRejectedReason: null,
    activated: false,
    credits: 0,
    txns: [],
    specialty: 'Life Coaching · Stress & Burnout',
    location: 'Online',
    formats: ['Online'],
    languages: ['English', 'Arabic'],
    about:
      'Sessions for busy professionals who want clarity, boundaries and a calmer week. Practical tools, no jargon.',
    profileCertifications: ['ICF Associate Certified Coach'],
    years: 5,
    style: 'Educational / explanatory',
    availability: 'Weekdays · Evenings',
    priceFrom: 'Quote on request',
    gender: 'female',
    rating: 4.9,
    reviews: 37,
    notificationPrefs: {...defaultNotificationPrefs, push: false, matchUpdates: false},
  },
];
