import type {QuoteRequest} from './types';

export const seedQuoteRequests: QuoteRequest[] = [
  {
    id: 'req-demo-1',
    clientId: 'client-yasmin',
    professionalId: 'amina-h',
    status: 'quoted',
    createdAt: '2026-08-14T10:00:00.000Z',
    quotedAt: '2026-08-15T09:30:00.000Z',
    closedAt: null,
    quoteMessage:
      'Happy to support your strength goals with 2–3 sessions per week. First session is a movement assessment.',
    quoteAmount: 'Quote on request',
  },
  {
    id: 'req-demo-2',
    clientId: 'client-yasmin',
    professionalId: 'omar-r',
    status: 'pending',
    createdAt: '2026-08-17T18:45:00.000Z',
    quotedAt: null,
    closedAt: null,
    quoteMessage: null,
    quoteAmount: null,
  },
  {
    id: 'req-reem-amina',
    clientId: 'client-reem',
    professionalId: 'amina-h',
    status: 'quoted',
    createdAt: '2026-08-11T08:20:00.000Z',
    quotedAt: '2026-08-12T11:00:00.000Z',
    closedAt: null,
    quoteMessage:
      'Pre/postnatal-friendly weight loss plan with 3 morning sessions. Gym or Dubai Marina outdoor options.',
    quoteAmount: 'Quote on request',
  },
  {
    id: 'req-tariq-omar',
    clientId: 'client-tariq',
    professionalId: 'omar-r',
    status: 'pending',
    createdAt: '2026-08-16T19:10:00.000Z',
    quotedAt: null,
    closedAt: null,
    quoteMessage: null,
    quoteAmount: null,
  },
  {
    id: 'req-dana-omar',
    clientId: 'client-dana',
    professionalId: 'omar-r',
    status: 'closed',
    createdAt: '2026-07-28T14:00:00.000Z',
    quotedAt: '2026-07-29T10:15:00.000Z',
    closedAt: '2026-08-01T16:00:00.000Z',
    quoteMessage: 'Corrective strength block focused on hip hinge and core stability.',
    quoteAmount: 'Quote on request',
  },
  {
    id: 'req-family-khalid',
    clientId: 'client-family',
    professionalId: 'khalid-b',
    status: 'pending',
    createdAt: '2026-08-18T08:00:00.000Z',
    quotedAt: null,
    closedAt: null,
    quoteMessage: null,
    quoteAmount: null,
  },
];
